# Generated by Django 3.2.3 on 2021-10-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oblist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campaign', models.CharField(max_length=20, verbose_name='战役')),
                ('Name', models.CharField(max_length=50, verbose_name='名称')),
                ('Phone1', models.CharField(max_length=50, verbose_name='号码1')),
                ('Phone2', models.CharField(blank=True, max_length=50, null=True, verbose_name='号码2')),
                ('Status', models.CharField(choices=[('未联系', '未联系'), ('未接通', '未接通'), ('拒绝沟通', '拒绝沟通'), ('再联系', '再联系'), ('有意向', '有意向'), ('有需求', '有需求')], default='未联系', max_length=20, verbose_name='状态')),
                ('Memo', models.TextField(null=True, verbose_name='备注')),
                ('Owner', models.CharField(choices=[('沈承永', '沈承永'), ('耿萌萌', '耿萌萌'), ('王志杰', '王志杰')], default='沈承永', max_length=40, verbose_name='执行人')),
            ],
            options={
                'verbose_name_plural': '外呼名单',
            },
        ),
    ]
