# Generated by Django 3.2.3 on 2021-10-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oblist',
            options={'verbose_name_plural': '电话营销'},
        ),
    ]
