# Generated by Django 3.2.3 on 2021-05-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miracle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zip', models.IntegerField(verbose_name='区号')),
                ('Number', models.IntegerField(verbose_name='固话号码')),
                ('Operator', models.IntegerField(choices=[(1, '中国电信'), (2, '中国联通'), (3, '中国移动'), (4, '中国铁通')], verbose_name='运营商')),
            ],
            options={
                'verbose_name_plural': '固话号码',
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
