# Generated by Django 3.2.3 on 2021-05-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miracle', '0002_auto_20210522_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixednumber',
            name='Zip',
            field=models.CharField(max_length=4, verbose_name='区号'),
        ),
    ]
