# Generated by Django 3.2.3 on 2021-05-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miracle', '0003_alter_fixednumber_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixednumber',
            name='Operator',
            field=models.CharField(choices=[('中国电信', '中国电信'), ('中国联通', '中国联通'), ('中国移动', '中国移动'), ('中国铁通', '中国铁通')], max_length=12, verbose_name='运营商'),
        ),
    ]
