# Generated by Django 3.2.3 on 2021-05-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miracle', '0004_alter_fixednumber_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixednumber',
            name='Status',
            field=models.CharField(choices=[('可选', '可选'), ('锁定', '锁定'), ('已售', '已售')], default='可选', max_length=8, verbose_name='状态'),
        ),
    ]
