# Generated by Django 3.2.3 on 2021-05-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miracle', '0005_fixednumber_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiracleOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=40, verbose_name='客户名称')),
                ('OrderDate', models.DateField(verbose_name='下单时间')),
                ('PBX_Type', models.CharField(max_length=10, verbose_name='交换机类型')),
                ('MCU_Type', models.CharField(max_length=10, verbose_name='多方通话许可')),
                ('API_Type', models.CharField(max_length=10, verbose_name='API许可')),
                ('APP_Number', models.IntegerField(verbose_name='APP许可数')),
                ('SIP_Number', models.IntegerField(verbose_name='SIP许可数')),
                ('Log_Number', models.IntegerField(verbose_name='录音许可数')),
                ('CC_Number', models.IntegerField(verbose_name='轻客服许可数')),
            ],
            options={
                'verbose_name_plural': 'Miracle订单',
            },
        ),
        migrations.AlterField(
            model_name='fixednumber',
            name='Zip',
            field=models.CharField(default='021', max_length=4, verbose_name='区号'),
        ),
    ]
