# Generated by Django 3.2.3 on 2021-05-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miracle', '0006_auto_20210522_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiracleCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=40, verbose_name='客户名称')),
                ('Year', models.CharField(max_length=4, verbose_name='年份')),
                ('Month', models.CharField(max_length=2, verbose_name='月份')),
                ('Cost', models.FloatField(verbose_name='金额')),
                ('RecordDate', models.DateTimeField(auto_now=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name_plural': 'Miracle话费',
            },
        ),
    ]
