# Generated by Django 3.2.3 on 2021-05-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miracle', '0007_miraclecost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miraclecost',
            options={'verbose_name_plural': 'Miracle话单'},
        ),
        migrations.AddField(
            model_name='miracleorders',
            name='Line_Number',
            field=models.IntegerField(default=0, verbose_name='并发数'),
        ),
        migrations.AddField(
            model_name='miracleorders',
            name='Number_0',
            field=models.IntegerField(default=0, verbose_name='普通号码数'),
        ),
        migrations.AddField(
            model_name='miracleorders',
            name='Number_1',
            field=models.IntegerField(default=0, verbose_name='1星号码数'),
        ),
        migrations.AddField(
            model_name='miracleorders',
            name='Number_2',
            field=models.IntegerField(default=0, verbose_name='2星号码数'),
        ),
        migrations.AddField(
            model_name='miracleorders',
            name='Number_3',
            field=models.IntegerField(default=0, verbose_name='3星号码数'),
        ),
        migrations.AddField(
            model_name='miracleorders',
            name='Number_4',
            field=models.IntegerField(default=0, verbose_name='4星号码数'),
        ),
        migrations.AddField(
            model_name='miracleorders',
            name='Number_5',
            field=models.IntegerField(default=0, verbose_name='5星号码数'),
        ),
    ]
