# Generated by Django 3.2.3 on 2021-05-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miracle', '0008_auto_20210523_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiracleBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=40, verbose_name='客户名称')),
                ('Year', models.CharField(max_length=4, verbose_name='年份')),
                ('Month', models.CharField(max_length=2, verbose_name='月份')),
                ('Bill_Cycle', models.CharField(max_length=2, verbose_name='计费周期')),
                ('Bill_Type', models.CharField(max_length=2, verbose_name='账单类型')),
                ('Bill', models.FloatField(verbose_name='账单金额')),
                ('RecordDate', models.DateTimeField(auto_now=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name_plural': 'Miracle账单',
            },
        ),
        migrations.CreateModel(
            name='MiracleCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=40, verbose_name='客户名称')),
                ('Year', models.CharField(max_length=4, verbose_name='年份')),
                ('Month', models.CharField(max_length=2, verbose_name='月份')),
                ('Credit', models.FloatField(verbose_name='消费金额')),
                ('RecordDate', models.DateTimeField(auto_now=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name_plural': 'Miracle话单',
            },
        ),
        migrations.RenameModel(
            old_name='FixedNumber',
            new_name='MiracleNumber',
        ),
        migrations.DeleteModel(
            name='MiracleCost',
        ),
        migrations.AlterModelOptions(
            name='miraclenumber',
            options={'verbose_name_plural': 'Miracle码号'},
        ),
    ]
