# Generated by Django 3.2.3 on 2021-05-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miracle', '0009_auto_20210523_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miracleorders',
            options={'verbose_name_plural': 'Miracle月租'},
        ),
        migrations.AddField(
            model_name='miracleorders',
            name='HPR_Number',
            field=models.IntegerField(default=0, verbose_name='话机月租数量'),
        ),
    ]
