# Generated by Django 3.2.3 on 2021-05-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miracle', '0010_auto_20210523_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miracleorders',
            name='OrderDate',
            field=models.DateTimeField(verbose_name='下单时间'),
        ),
    ]
