# Generated by Django 3.2.3 on 2021-05-24 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Miracle', '0012_contact_organize'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacts',
        ),
        migrations.RenameModel(
            old_name='Organize',
            new_name='Organization',
        ),
    ]
