# Generated by Django 3.2.3 on 2021-05-24 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Miracle', '0013_auto_20210524_1022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
