# Generated by Django 3.2.3 on 2021-05-27 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Miracle', '0014_auto_20210524_1027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='miraclenumber',
            unique_together={('Zip', 'Number')},
        ),
    ]
