# Generated by Django 3.2.3 on 2021-06-07 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_organization_organizeid'),
        ('Miracle', '0017_miraclebill_memo'),
    ]

    operations = [

    ]
