# Generated by Django 3.2.3 on 2021-06-07 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_organization_organizeid'),
        ('Miracle', '0019_auto_20210607_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miraclebill',
            name='CustomerID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.organization'),
        ),
    ]
