# Generated by Django 3.2.3 on 2021-06-07 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_organization_organizeid'),
        ('Miracle', '0020_alter_miraclebill_customerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miraclebill',
            name='CustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.organization', verbose_name='客户名称'),
        ),
    ]
