# Generated by Django 3.2.3 on 2021-06-07 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Miracle', '0022_auto_20210607_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miracleorders',
            options={'verbose_name_plural': 'Miracle订单'},
        ),
    ]
