# Generated by Django 3.2.3 on 2021-06-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miracle', '0024_alter_miraclebill_bill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='miraclebill',
            name='Bill_Status',
            field=models.CharField(choices=[('已出账', '已出账'), ('已到账', '已到账'), ('已坏账', '已坏账')], default='已出账', max_length=8, verbose_name='账单状态'),
        ),
        migrations.AddField(
            model_name='miraclebill',
            name='UpdateDate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='miraclebill',
            name='Bill_Type',
            field=models.CharField(choices=[('租金', '租金'), ('话费', '话费')], default='租金', max_length=4, verbose_name='账单类型'),
        ),
    ]
