# Generated by Django 3.2.3 on 2021-06-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miracle', '0025_auto_20210611_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miraclebill',
            name='RecordDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='miraclebill',
            name='UpdateDate',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
