# Generated by Django 3.2.3 on 2021-06-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miracle', '0026_auto_20210611_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='miraclenumber',
            name='Stars',
            field=models.CharField(choices=[('普通号', '普通号'), ('1星级', '1星级'), ('2星级', '2星级'), ('3星级', '3星级'), ('4星级', '4星级'), ('5星级', '5星级')], default='普通号', max_length=8, verbose_name='星级'),
        ),
    ]
