# Generated by Django 3.2.3 on 2021-08-02 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_auto_20210802_1317'),
        ('Miracle', '0027_miraclenumber_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miracleorders',
            name='CustomerName',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='crm.organization', verbose_name='客户名称'),
        ),
    ]
