# Generated by Django 3.2.3 on 2021-09-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miracle', '0029_auto_20210901_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miraclenumber',
            name='Number',
            field=models.CharField(max_length=8, verbose_name='固话号码'),
        ),
    ]
