# Generated by Django 3.2.3 on 2021-10-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miracle', '0030_alter_miraclenumber_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='miracleorders',
            name='OrderType',
            field=models.CharField(choices=[('月付', '月付'), ('季付', '季付'), ('半年付', '半年付'), ('年付', '年付')], default='月付', max_length=10, verbose_name='订单类型'),
        ),
        migrations.AlterField(
            model_name='miracleorders',
            name='OrderDate',
            field=models.DateTimeField(verbose_name='生效时间'),
        ),
    ]
