# Generated by Django 3.2.3 on 2021-10-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miracle', '0031_auto_20211004_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miracleorders',
            name='OrderType',
            field=models.CharField(choices=[('新增', '新增'), ('退订', '退订')], default='新增', max_length=10, verbose_name='订单类型'),
        ),
    ]
