# Generated by Django 3.2.3 on 2021-10-06 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_alter_contacthistory_options'),
        ('Miracle', '0032_alter_miracleorders_ordertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiraclePBX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server', models.CharField(max_length=50, verbose_name='服务器')),
                ('PBX', models.CharField(max_length=30, verbose_name='企业编号')),
                ('RecordDate', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('UpdateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('Memo', models.TextField(default='无', verbose_name='备注')),
                ('Customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.organization', verbose_name='客户名称')),
            ],
            options={
                'verbose_name_plural': 'Miracle交换',
            },
        ),
        migrations.CreateModel(
            name='MiracleDID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server', models.CharField(max_length=50, verbose_name='服务器')),
                ('PBX', models.CharField(max_length=30, verbose_name='企业编号')),
                ('DID', models.CharField(max_length=30, verbose_name='直线账户')),
                ('RecordDate', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('UpdateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('Memo', models.TextField(default='无', verbose_name='备注')),
                ('Customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.organization', verbose_name='客户名称')),
            ],
            options={
                'verbose_name_plural': 'Miracle直线',
            },
        ),
    ]
