# Generated by Django 3.2.3 on 2021-10-06 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_alter_contacthistory_options'),
        ('Miracle', '0033_miracledid_miraclepbx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miraclecredit',
            name='CustomerID',
        ),
        migrations.AddField(
            model_name='miraclecredit',
            name='Account',
            field=models.CharField(max_length=50, null=True, verbose_name='账户名称'),
        ),
        migrations.AddField(
            model_name='miraclecredit',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.organization', verbose_name='客户名称'),
        ),
        migrations.AddField(
            model_name='miraclecredit',
            name='Type',
            field=models.CharField(max_length=10, null=True, verbose_name='账户类型'),
        ),
    ]
