# Generated by Django 3.2.3 on 2021-10-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miracle', '0034_auto_20211006_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='miraclecredit',
            name='Memo',
            field=models.TextField(default='无', verbose_name='备注'),
        ),
    ]
