# Generated by Django 3.2.3 on 2021-06-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210527_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('u', '未开始'), ('o', '进行中'), ('f', '已完成')], max_length=1, verbose_name='状态'),
        ),
    ]
