# Generated by Django 3.2.3 on 2021-06-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('未开始', '未开始'), ('进行中', '进行中'), ('已完成', '已完成')], max_length=8, verbose_name='状态'),
        ),
    ]
