# Generated by Django 3.2.3 on 2021-06-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='User',
        ),
        migrations.AddField(
            model_name='task',
            name='Creator',
            field=models.CharField(default='匿名', max_length=40, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='task',
            name='createdtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updatedtime',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
