# Generated by Django 3.2.3 on 2021-06-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20210611_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Creator',
            field=models.CharField(default='沈承永', max_length=40, verbose_name='创建人'),
        ),
    ]
