# Generated by Django 3.2.3 on 2021-07-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Owner',
            field=models.CharField(default='沈承永', max_length=40, verbose_name='执行人'),
        ),
    ]
