# Generated by Django 3.2.3 on 2021-08-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_task_tasktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Owner',
            field=models.CharField(choices=[('沈承永', '沈承永'), ('耿萌萌', '耿萌萌'), ('王忠盟', '王忠盟')], default='沈承永', max_length=40, verbose_name='执行人'),
        ),
    ]
