# Generated by Django 3.2.3 on 2021-05-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, verbose_name='姓名')),
                ('Mobile', models.IntegerField(verbose_name='手机号')),
                ('Email', models.EmailField(max_length=254, verbose_name='电子邮件')),
                ('Memo', models.TextField(verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '联系人',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganizeName', models.CharField(max_length=60, verbose_name='组织名称')),
                ('OrganizeID', models.CharField(max_length=60, verbose_name='组织代码')),
                ('Memo', models.TextField(verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '组织',
            },
        ),
    ]
