# Generated by Django 3.2.3 on 2021-05-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, verbose_name='姓名')),
                ('ContactDateTime', models.DateTimeField(verbose_name='联系时间')),
                ('ContactMedia', models.CharField(max_length=20, verbose_name='联系方式')),
                ('Memo', models.TextField(verbose_name='联系内容')),
            ],
            options={
                'verbose_name_plural': '联系记录',
            },
        ),
    ]
