# Generated by Django 3.2.3 on 2021-06-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_contacthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='OrganizeID',
            field=models.CharField(max_length=60, unique=True, verbose_name='组织代码'),
        ),
    ]
