# Generated by Django 3.2.3 on 2021-06-07 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_organization_organizeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='Organize',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='crm.organization', verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='contacthistory',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.contacts', verbose_name='姓名'),
        ),
    ]
