# Generated by Django 3.2.3 on 2021-06-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_rename_name_contacthistory_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacthistory',
            name='ContactDateTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='联系时间'),
        ),
        migrations.AlterField(
            model_name='contacthistory',
            name='ContactMedia',
            field=models.CharField(max_length=20, null=True, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='contacthistory',
            name='Memo',
            field=models.TextField(null=True, verbose_name='联系内容'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Email',
            field=models.EmailField(max_length=254, null=True, verbose_name='电子邮件'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Memo',
            field=models.TextField(null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Mobile',
            field=models.IntegerField(null=True, verbose_name='手机号'),
        ),
    ]
