# Generated by Django 3.2.3 on 2021-07-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20210611_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='Mobile',
            field=models.CharField(max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
