# Generated by Django 3.2.3 on 2021-07-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_contacts_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oblist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, verbose_name='名称')),
                ('Number1', models.CharField(max_length=11, null=True, verbose_name='号码1')),
                ('Number2', models.CharField(max_length=11, null=True, verbose_name='号码2')),
                ('Status', models.CharField(max_length=20, verbose_name='状态')),
                ('Memo', models.TextField(null=True, verbose_name='备注')),
            ],
        ),
    ]
