# Generated by Django 3.2.3 on 2021-07-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20210722_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oblist',
            name='Campaign',
            field=models.CharField(max_length=20, verbose_name='战役'),
        ),
    ]
