# Generated by Django 3.2.3 on 2021-07-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_oblist_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oblist',
            name='Phone1',
            field=models.CharField(max_length=50, verbose_name='号码1'),
        ),
        migrations.AlterField(
            model_name='oblist',
            name='Phone2',
            field=models.CharField(max_length=50, null=True, verbose_name='号码2'),
        ),
    ]
