# Generated by Django 3.2.3 on 2021-07-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20210722_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oblist',
            name='Name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
    ]
