# Generated by Django 3.2.3 on 2021-07-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_oblist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='oblist',
            name='Owner',
            field=models.CharField(choices=[('沈承永', '沈承永'), ('耿萌萌', '耿萌萌')], default='沈承永', max_length=40, verbose_name='执行人'),
        ),
    ]
