# Generated by Django 3.2.3 on 2021-09-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_auto_20210802_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oblist',
            name='Owner',
            field=models.CharField(choices=[('沈承永', '沈承永'), ('耿萌萌', '耿萌萌'), ('王志杰', '王志杰')], default='沈承永', max_length=40, verbose_name='执行人'),
        ),
    ]
