# Generated by Django 3.2.3 on 2021-10-03 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Park', '0003_auto_20211003_0913'),
        ('crm', '0018_alter_oblist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='Park',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Park.park', verbose_name='园区'),
        ),
    ]
