# Generated by Django 3.2.3 on 2021-10-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_organization_park'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Oblist',
        ),
    ]
