# Generated by Django 3.2.3 on 2021-10-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_delete_oblist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacthistory',
            options={'verbose_name_plural': '沟通历史'},
        ),
    ]
