# Generated by Django 3.2.3 on 2021-09-30 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CloudNet', '0002_auto_20210930_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='Device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CloudNet.device', verbose_name='设备'),
        ),
    ]
