# Generated by Django 3.2.3 on 2021-09-30 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_oblist_owner'),
        ('CloudNet', '0003_card_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudNet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateTimeField(verbose_name='开始时间')),
                ('EndDate', models.DateTimeField(verbose_name='结束时间')),
                ('RecordDate', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('UpdateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('Memo', models.TextField(default='库存', verbose_name='备注')),
                ('Device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CloudNet.device', verbose_name='设备')),
                ('Organize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.organization', verbose_name='客户')),
            ],
            options={
                'verbose_name_plural': '云宽带',
            },
        ),
    ]
