# Generated by Django 3.2.3 on 2021-09-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudNet', '0004_cloudnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudnet',
            name='EndDate',
            field=models.DateField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='cloudnet',
            name='StartDate',
            field=models.DateField(verbose_name='开始时间'),
        ),
    ]
