# Generated by Django 3.2.3 on 2021-09-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudNet', '0005_auto_20210930_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='CardNumber',
            field=models.CharField(max_length=19, unique=True, verbose_name='卡号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='Mac',
            field=models.CharField(max_length=17, unique=True, verbose_name='Mac地址'),
        ),
        migrations.AlterField(
            model_name='device',
            name='SN',
            field=models.CharField(max_length=19, null=True, verbose_name='SN码'),
        ),
    ]
