# Generated by Django 3.2.3 on 2021-09-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudNet', '0006_auto_20210930_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='Type',
            field=models.CharField(choices=[('YQ-212-OP', 'YQ-212-OP'), ('C3000', 'C3000'), ('C2000', 'C2000'), ('YQ-4001', 'YQ-4001'), ('YQ-4002', 'YQ-4002')], default='YQ-4001', max_length=12, verbose_name='设备型号'),
        ),
    ]
