# Generated by Django 3.2.3 on 2021-09-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudNet', '0007_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30, verbose_name='工单名称')),
                ('Type', models.CharField(choices=[('新装', '新装'), ('维修', '维修'), ('加装', '加装'), ('拆机', '拆机'), ('其他', '其他')], default='新装', max_length=12, verbose_name='工单类型')),
                ('Content', models.TextField(null=True, verbose_name='工单内容')),
                ('Worker', models.CharField(choices=[('胡开竹', '胡开竹'), ('刘梓妍', '刘梓妍'), ('其他', '其他')], default='胡开竹', max_length=12, verbose_name='施工人员')),
                ('DateTime', models.DateTimeField(verbose_name='施工时间')),
                ('RecordDate', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('UpdateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('Memo', models.TextField(default='无', verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '服务工单',
            },
        ),
        migrations.AlterField(
            model_name='device',
            name='Type',
            field=models.CharField(choices=[('YQ-212-OP', 'YQ-212-OP'), ('C3000', 'C3000'), ('C2000', 'C2000'), ('YQ-4001', 'YQ-4001'), ('YQ-4002', 'YQ-4002')], default='YQ-212-OP', max_length=12, verbose_name='设备型号'),
        ),
    ]
