# Generated by Django 3.2.3 on 2021-09-30 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_oblist_owner'),
        ('CloudNet', '0008_auto_20210930_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='Organize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.organization', verbose_name='客户'),
        ),
    ]
