# Generated by Django 3.2.3 on 2021-10-03 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PMName', models.CharField(max_length=50, unique=True, verbose_name='园区管理员名称')),
                ('RecordDate', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('UpdateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('Memo', models.TextField(default='无', verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '园区管理员',
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParkName', models.CharField(max_length=50, unique=True, verbose_name='园区名称')),
                ('RecordDate', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('UpdateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('Memo', models.TextField(default='无', verbose_name='备注')),
                ('PM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Park.parkmanager', verbose_name='园区管理员')),
            ],
            options={
                'verbose_name_plural': '园区管理',
            },
        ),
    ]
