# Generated by Django 3.2.3 on 2021-10-03 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Park', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StreetName', models.CharField(max_length=50, unique=True, verbose_name='街道名称')),
                ('RecordDate', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('UpdateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('Memo', models.TextField(default='无', verbose_name='备注')),
            ],
        ),
        migrations.AlterModelOptions(
            name='parkmanager',
            options={},
        ),
        migrations.AddField(
            model_name='park',
            name='No',
            field=models.CharField(max_length=10, null=True, verbose_name='门牌号'),
        ),
        migrations.AddField(
            model_name='park',
            name='Street',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Park.street', verbose_name='街道'),
        ),
    ]
