# Generated by Django 3.2.3 on 2021-10-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Park', '0005_auto_20211005_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='No',
        ),
        migrations.AddField(
            model_name='park',
            name='City',
            field=models.CharField(max_length=50, null=True, verbose_name='市'),
        ),
        migrations.AddField(
            model_name='park',
            name='District',
            field=models.CharField(max_length=50, null=True, verbose_name='区县'),
        ),
        migrations.AddField(
            model_name='park',
            name='Province',
            field=models.CharField(max_length=50, null=True, verbose_name='省'),
        ),
        migrations.AlterField(
            model_name='park',
            name='Street',
            field=models.CharField(max_length=50, null=True, verbose_name='乡镇街道'),
        ),
    ]
