# Generated by Django 3.2.3 on 2021-10-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Park', '0006_auto_20211005_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Street',
        ),
        migrations.AlterModelOptions(
            name='park',
            options={'verbose_name_plural': '园区'},
        ),
        migrations.AlterModelOptions(
            name='parklog',
            options={'verbose_name_plural': '园区开发记录'},
        ),
        migrations.AlterField(
            model_name='park',
            name='City',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='市'),
        ),
        migrations.AlterField(
            model_name='park',
            name='District',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='区县'),
        ),
        migrations.AlterField(
            model_name='park',
            name='Province',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='省'),
        ),
        migrations.AlterField(
            model_name='park',
            name='Street',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='乡镇街道'),
        ),
    ]
