# Generated by Django 3.2.3 on 2021-10-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Park', '0007_auto_20211006_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parklog',
            options={'verbose_name_plural': '开发历史'},
        ),
    ]
